<div id="paytrail-form-wrapper"></div>
<script>
    window.addEventListener('checkout:init:evaluation', event => {
        hyvaCheckout.evaluation.registerExecutable(
            'my-form-action',
            (result, element, component) => {
                document.getElementById('paytrail-form-wrapper').innerHTML = result.arguments.params.html_data;
                document.getElementById("checkout_form").submit();
            }
        );
    })

    function paytrailPaymentMethod() {
        const method = this.$el.dataset.method;

        return {
            setPaymentMethod() {
                this.$wire.setPaymentMethod(method);
            },
        }
    }

    window.addEventListener(
        'alpine:init',
        () => Alpine.data('paytrailPaymentMethod', paytrailPaymentMethod),
        {once: true}
    )
</script>
<?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
